---
- name: Create User exporter
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    create_home: no
    shell: /bin/false

- name: Create directories
  ansible.builtin.file:
    path: "{{ node_exporter_install_dir }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: '0755'

- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: "{{ node_exporter_install_dir }}"
    remote_src: yes
    extra_opts: ["--strip-components=1"]
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"    

- name: Copy Node Exporter systemd service file
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Ensure Node Exporter service is enabled and started
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: yes

- name: Add Node Exporter target to Prometheus configuration
  ansible.builtin.blockinfile:
    path: "{{ prometheus_config_dir }}/prometheus.yml"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Node Exporter Targets"
    block: |
      - job_name: 'node_exporter'
        static_configs:
          - targets:
            {% for host in groups['nodes'] %}
              - "{{ host }}:{{ node_exporter_port }}"
            {% endfor %}
    create: yes
    insertafter: "^scrape_configs:"
  delegate_to: "{{ groups['server'][0] }}" 
  notify: Restart Prometheus

- name: Ensure Prometheus service is enabled and started
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes