---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Elasticsearch
  ansible.builtin.service:
    name: elasticsearch
    state: restarted

- name: Restart Kibana
  ansible.builtin.service:
    name: kibana
    state: restarted