elasticsearch_version: "7.17.0"
elasticsearch_install_dir: "/usr/share/elasticsearch"
elasticsearch_config_dir: "/etc/elasticsearch"
elasticsearch_data_dir: "/var/lib/elasticsearch"
elasticsearch_log_dir: "/var/log/elasticsearch"
elasticsearch_user: "elasticsearch"
elasticsearch_group: "elasticsearch"
elasticsearch_heap_size: "2g"
elasticsearch_host: "localhost:9200"

kibana_version: "7.17.0"
kibana_install_dir: "/usr/share/kibana"
kibana_config_dir: "/etc/kibana"
kibana_log_dir: "/var/log/kibana"
kibana_user: "kibana"
kibana_group: "kibana"
kibana_server_host: "0.0.0.0"
