---
- name: "install prometheus"  
  hosts: server
  become: true
  roles:
     - prometheus
     - elastic-kibana



- name: "install exorters"  
  hosts: nodes
  become: true
  roles:
    - node-exporter
    - fluentbit